<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
   <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>

    <AssemblyName>HeavenlyCVR</AssemblyName>
    <RootNamespace>HeavenlyCVR</RootNamespace>

    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>

    <Reference Include="MelonLoader">
      <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/MelonLoader/net472/MelonLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="CVRLogger">
      <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/CVRLogger.dll</HintPath>
      <Private>false</Private>
    </Reference>

<Reference Include="UIExpansionKit">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/Mods/UI Expansion Kit.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="UnityEngine.CoreModule">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="UnityEngine.UI">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/UnityEngine.UI.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="UnityEngine.UIModule">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/UnityEngine.UIModule.dll</HintPath>
  <Private>false</Private>
</Reference>
   
<Reference Include="UnityEngine.TextRenderingModule">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/UnityEngine.TextRenderingModule.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="UnityEngine.AnimationModule">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/UnityEngine.AnimationModule.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="UnityEngine.PhysicsModule">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/UnityEngine.PhysicsModule.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="UnityEngine.InputLegacyModule">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/UnityEngine.InputLegacyModule.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="ECM2">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/ECM2.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="Unity.TextMeshPro">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/Unity.TextMeshPro.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="UnityEngine.IMGUIModule">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/UnityEngine.IMGUIModule.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="UnityEngine.AudioModule">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/UnityEngine.AudioModule.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="MagicaCloth">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/MagicaCloth.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="MagicaClothV2">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/MagicaClothV2.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="Newtonsoft.Json">  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/Newtonsoft.Json.dll</HintPath>
  <Private>false</Private>
</Reference>

<Reference Include="UnityEngine.ParticleSystemModule">
  <HintPath>/home/notsecrets/.local/share/Steam/steamapps/common/ChilloutVR/ChilloutVR_Data/Managed/UnityEngine.ParticleSystemModule.dll</HintPath>
  <Private>false</Private>
</Reference>


  </ItemGroup>

</Project>
